### ISSUE TITLE
Vercel build fails

### ISSUE THREAD

**Issue by bgondell** [goncy/store#6]
Todavía no sé de Next.JS como para poder debbugear, se agradece cualquier ayuda, busco probar y aprender con esta tienda.
Seguí las instrucciones, no supe que poner en Fields en env.local y coloqué "TestingField".

```
PRODUCTS=https://docs.google.com/spreadsheets/d/e/2PACX-1vROqt3G7oNAF9bwmA8Bl8464qfDS8B4GqAPRIVwmBYT9bghMbcRJv3H0Uv8Ko82jo-fW-5HOSLhOkqm/pub?output=csv
FIELDS=TestingField
STORE=Goncy-Store
SECRET=goncy
COLOR=teal
```

Vercel falla en el build, muchos errores con "code: 'ERR_INVALID_URL'" y terminando con este mensaje:

```
> Export encountered errors on following paths:
--
14:45:49.608 | /[product]/page: /0001
14:45:49.608 | /[product]/page: /0002
14:45:49.608 | /[product]/page: /0003
14:45:49.608 | /[product]/page: /0004
14:45:49.608 | /[product]/page: /0005
14:45:49.608 | /_not-found
14:45:49.608 | /page: /
```

Muchas gracias por todo aporte!!

**Comment by doxxen** [comment]
Buenas como estas?

Estas pifiando. En fields , store tenes que colocar el link en csv de cada seccion del google sheets. y secret es el tiempo de refresh

**Comment by bgondell** [comment]
Hola @doxxen , gracias por tu respuesta!
Disculpá la demora, me quedaba pendiente probar tu respuesta. Aún no me quedó en claro... sería demasiado pedirte un ejemplo?
Mil gracias!

**Comment by bgondell** [comment]
Got it!!

Ya entendí que en cada campo hay que poner el CSV según la pestaña.
Lo que me pareció raro es que cuando ponía en el drive "entire document" y export csv, solo exportaba la pestana de productos.

En definitiva, en el proceso de publish to web, copien y peguen la url por cada sección en el env.
Si se fijan, cambia el gid, que es el id de cada pestaña en la planilla.

Ejemplo:

`PRODUCTS=https://docs.google.com/spreadsheets/d/e/xxxxxxxxxxxxxxx/pub?gid=0&single=true&output=csv
FIELDS=https://docs.google.com/spreadsheets/d/e/xxxxxxxxxxxxxxx/pub?gid=1947094682&single=true&output=csv
STORE=https://docs.google.com/spreadsheets/d/e/xxxxxxxxxxxxxxx/pub?gid=988571459&single=true&output=csv
SECRET=10
COLOR=teal`
